### ISSUE TITLE
Chapter headings are too big in handrit theme

### ISSUE THREAD

**Issue by shunn** [DaveJarvis/keenwrite-themes#3]
Looking at the output of the handrit theme, I noticed that chapter headings were in a much larger font than the rest of the text. Classic manuscript format is meant to simulate the output of a typewriter, and a typewriter does not have variable font sizes. Chapter headings should be centered on the line, not bolded, and rendered in the same size font as the rest of the text.

**Comment by DaveJarvis** [comment]
Fixed on main.
