### ISSUE TITLE
Word count not rounded for handrit theme

### ISSUE THREAD

**Issue by shunn** [DaveJarvis/keenwrite-themes#5]
Looking at the output of the handrit theme, I noticed that the word count on the title page was not rounded. If the goal is to output a document in classic manuscript format that could be submitted to a publisher, then the word count should be rounded. I'd suggest breakdowns like this:

0 - 2,500 words:  round to nearest 100
2,500 to 10,000 words:  round to nearest 500
10,000 to 40,000 words:  round to nearest 1,000
40,000 and up:  round to nearest 5,000

**Comment by DaveJarvis** [comment]
Fixed on main. Will be in next release.
